doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: 'mariadb-10.5.8'
                charset: utf8mb4
            pemba:
                # configure these for your database server
                url: '%env(resolve:DATABASE_PEMBA_URL)%'
                driver: 'pdo_mysql'
                server_version: 'mariadb-10.3.37'
                charset: latin1
            meddra:
                # configure these for your database server
                url: '%env(resolve:DATABASE_MEDDRA_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.5.27'
                charset: latin1

        # url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
    #     auto_generate_proxy_classes: true
    #     naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    #     auto_mapping: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            pemba:
                connection: pemba
                mappings:
                    Codex:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Pemba'
                        prefix: 'App\Entity\Pemba'
                        alias: Pemba
            meddra:
                connection: meddra
                mappings:
                    Codex:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Meddra'
                        prefix: 'App\Entity\Meddra'
                        alias: Meddra



    # orm:
    #     auto_generate_proxy_classes: true
    #     naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    #     auto_mapping: true
    #     mappings:
    #         App:
    #             is_bundle: false
    #             dir: '%kernel.project_dir%/src/Entity'
    #             prefix: 'App\Entity'
    #             alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
